/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package arv.former;

import java.awt.Graphics;
import java.util.ArrayList;

/**
 *
 * @author khaok01
 */
public class FormerJPanel extends javax.swing.JPanel implements Runnable {

    ArrayList<Form> Former = new ArrayList<>();
    FileManager fmgr = new FileManager();
    boolean Animering = true;
    private volatile Thread trad;
    boolean running;

    /**
     * Creates new form FormerJPanel
     */
    public FormerJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtng1 = new javax.swing.ButtonGroup();
        btnRensa = new javax.swing.JButton();
        rbtnTriangel = new javax.swing.JRadioButton();
        rbtnRektangel = new javax.swing.JRadioButton();
        rbtnCirkel = new javax.swing.JRadioButton();
        btnSpara = new javax.swing.JButton();
        btnHämta = new javax.swing.JButton();
        tbtnAnimering = new javax.swing.JToggleButton();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        btnRensa.setText("Rensa");
        btnRensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRensaActionPerformed(evt);
            }
        });

        rbtng1.add(rbtnTriangel);
        rbtnTriangel.setSelected(true);
        rbtnTriangel.setText("Triangel");

        rbtng1.add(rbtnRektangel);
        rbtnRektangel.setText("Rektangel");

        rbtng1.add(rbtnCirkel);
        rbtnCirkel.setText("Cirkel");

        btnSpara.setText("Spara");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        btnHämta.setText("Hämta");
        btnHämta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHämtaActionPerformed(evt);
            }
        });

        tbtnAnimering.setText("Start");
        tbtnAnimering.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tbtnAnimeringItemStateChanged(evt);
            }
        });
        tbtnAnimering.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnAnimeringActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtnTriangel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnRektangel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnCirkel)
                        .addGap(18, 18, 18)
                        .addComponent(tbtnAnimering, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRensa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnHämta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSpara)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnTriangel)
                    .addComponent(rbtnRektangel)
                    .addComponent(rbtnCirkel)
                    .addComponent(btnRensa)
                    .addComponent(tbtnAnimering))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSpara)
                    .addComponent(btnHämta))
                .addContainerGap(248, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRensaActionPerformed
        this.Former.clear();
        repaint();
    }//GEN-LAST:event_btnRensaActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        int x = evt.getX();
        int y = evt.getY();
        int b = (int) (Math.random() * 301) + 5;
        int h = (int) (Math.random() * 301) + 5;
        if (this.rbtnTriangel.isSelected()) {
            Form t = new Triangel(y + (h / 2), x - (b / 2), b, h, true);
            Former.add(t);
        } else if (this.rbtnRektangel.isSelected()) {
            Form r = new Rektangel(y - (h / 2), x - (b / 2), b, h, true);
            Former.add(r);
        } else if (this.rbtnCirkel.isSelected()) {
            Form c = new Cirkel(y - (h / 2), x - (h / 2), h, true);
            Former.add(c);
        }
        repaint();
    }//GEN-LAST:event_formMouseClicked

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        fmgr.saveToFile(Former);
    }//GEN-LAST:event_btnSparaActionPerformed

    private void btnHämtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHämtaActionPerformed
        Former = fmgr.readFromFile();
        repaint();
    }//GEN-LAST:event_btnHämtaActionPerformed

    private void tbtnAnimeringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnAnimeringActionPerformed
        if (Animering) {
            tbtnAnimering.setText("Stop");
            start();
            Animering = false;
        } else {
            tbtnAnimering.setText("Start");
            stop();
            Animering = true;
        }
        run();
    }//GEN-LAST:event_tbtnAnimeringActionPerformed

    private void tbtnAnimeringItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tbtnAnimeringItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtnAnimeringItemStateChanged
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        for (int i = 0; i < Former.size(); i++) {
            Former.get(i).draw(g);
        }
    }

    private void start() {
        if (trad == null) {
            trad = new Thread(this);
            trad.start();
            this.running = true;
        }
    }

    private void stop() {
        if (trad != null) {
            this.running = false;
            trad = null;
        }
    }

    @Override
    public void run() {
        Thread thisThread = Thread.currentThread();
        while (trad == thisThread) {
            try {
                Thread.sleep(30);
            } catch (InterruptedException e) {
            }
            repaint();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHämta;
    private javax.swing.JButton btnRensa;
    private javax.swing.JButton btnSpara;
    private javax.swing.JRadioButton rbtnCirkel;
    private javax.swing.JRadioButton rbtnRektangel;
    private javax.swing.JRadioButton rbtnTriangel;
    private javax.swing.ButtonGroup rbtng1;
    private javax.swing.JToggleButton tbtnAnimering;
    // End of variables declaration//GEN-END:variables
}
